### ISSUE TITLE
Video Encoder error on Full Test

### ISSUE THREAD

**Issue by EDelfosse** [bitbrawl/foodfight#3]
Hey, sorry to bother you once again,
So now when I run the FullTest, the match works properly, which i can see in the trace.json file however i receive this error after "Generating video":
20:18:28.737 [INFO] Generating video
Exception in thread "main" java.lang.NoClassDefFoundError: io/humble/video/Coder
	at org.bitbrawl.foodfight.engine.GameEngine.runMatch(GameEngine.java:165)
	at org.bitbrawl.foodfight.engine.GameEngine.runMatches(GameEngine.java:70)
	at org.bitbrawl.foodfighter.FullTest.main(FullTest.java:27)
Caused by: java.lang.ClassNotFoundException: io.humble.video.Coder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 3 more

Both player data files are empty however it does seem that the match worked fine because the trace.json shows movement and interaction. So just the video encoder is making an error.
Thanks

**Comment by fvoichick** [comment]
Hmm... I'm having trouble replicating this problem. To verify, you're running it from within Eclipse?

I'll continue to look into this, but this shouldn't affect matches on the server, so if the behavior in `DebugTest` is what you want, and the match itself completed successfully, you can go ahead and submit.

**Comment by EDelfosse** [comment]
Yah i'm it in Eclipse. Do you know how often the bitbrawl leaderboard
refreshes because I can't see my username on it.

**Comment by fvoichick** [comment]
You need to update the `version` in the **src/main/java/config.json** file. Once you do this and commit/push, your code will begin being randomly selected for matches, and you will start showing up on the leaderboard.
